from __future__ import annotations

import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import typer

from ggbot.runtime.agent_loop import ToolLimits, run_query
from ggbot.app.app_bootstrap import create_agent_bootstrap, create_app_session
from ggbot.app.config import Settings
from ggbot.api.permission_manager import get_permission_manager
from ggbot.events.runtime_events import consume_runtime_events
from ggbot.tools.registry import ToolRegistry
from ggbot.state.transcript import Transcript
from ggbot.models.protocol_models import ChatMessage

# ANSI color codes for log highlighting
COLOR_RESET = "\033[0m"
COLOR_BOLD = "\033[1m"
COLOR_DIM = "\033[2m"
COLOR_RED = "\033[31m"
COLOR_GREEN = "\033[32m"
COLOR_YELLOW = "\033[33m"
COLOR_BLUE = "\033[34m"
COLOR_MAGENTA = "\033[35m"
COLOR_CYAN = "\033[36m"
COLOR_WHITE = "\033[37m"

app = typer.Typer(add_completion=False, help="GGbot - minimal CLI agent")


@app.callback()
def _main(
    debug: bool = typer.Option(
        False,
        "--debug",
        help="Show pretty Rich tracebacks (includes locals) on crashes.",
    ),
) -> None:
    if not debug:
        return

    from rich.traceback import install

    install(show_locals=True)


def _default_system_message() -> ChatMessage:
    return ChatMessage(
        role="system",
        content=(
            "You are GGbot, a helpful coding CLI agent. "
            "Use available tools when needed. "
            "When using tools, be concise and safe."
        ),
    )


def _print_delta(text: str) -> None:
    sys.stdout.write(text)
    sys.stdout.flush()


def _print_tool_output(name: str, output: str) -> None:
    print("")
    print(f"[tool:{name}]")
    print(output)
    print(f"[/tool:{name}]")


def _make_api_shell_confirm_callback(logger):
    """Create shell confirmation callback for API mode with frontend approval."""

    permission_manager = get_permission_manager()

    def _confirm(command: str) -> str | None:
        allowed, reason, request_id = permission_manager.request(
            tool_name="shell_run",
            arguments={"command": command},
        )
        if allowed:
            logger.info(f"API mode approved shell_run: request_id={request_id}")
            return None

        deny_reason = reason or "Cancelled by API user."
        logger.warning(f"API mode denied shell_run: request_id={request_id} reason={deny_reason}")
        return deny_reason

    return _confirm


def _global_env_file() -> Path:
    return (Path.home() / ".ggbot" / ".env").resolve()


def _env_template_file() -> Path:
    return (Path(__file__).resolve().parent.parent / ".env.example").resolve()


def _render_env_from_template(
    *,
    template: str,
    api_key: str | None,
    base_url: str,
    model: str,
) -> str:
    replacements: dict[str, str | None] = {
        "OPENAI_MODEL": model,
        "OPENAI_API_KEY": api_key,
        "OPENAI_BASE_URL": base_url,
    }
    replaced: set[str] = set()
    out: list[str] = []

    for line in template.splitlines():
        updated = line
        for key, value in replacements.items():
            if key in replaced:
                continue
            pattern = rf"^\s*#?\s*{re.escape(key)}\s*=.*$"
            if not re.match(pattern, line):
                continue

            if key == "OPENAI_API_KEY" and (value is None or not value.strip()):
                updated = f"# {key}=sk-your-key-here"
            else:
                updated = f"{key}={value}"
            replaced.add(key)
            break
        out.append(updated)

    # Ensure keys exist even if template format changes.
    for key, value in replacements.items():
        if key in replaced:
            continue
        if key == "OPENAI_API_KEY" and (value is None or not value.strip()):
            out.append(f"# {key}=sk-your-key-here")
        else:
            out.append(f"{key}={value}")

    return "\n".join(out).rstrip() + "\n"


def _write_global_env_file(
    *,
    env_file: Path,
    api_key: str | None,
    base_url: str,
    model: str,
) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    template_path = _env_template_file()
    if template_path.exists():
        template = template_path.read_text(encoding="utf-8")
    else:
        template = (
            "# GGbot environment\n"
            "# Generated by `ggbot init`\n"
            "# OPENAI_API_KEY=sk-your-key-here\n"
            "# OPENAI_BASE_URL=https://api.openai.com/v1\n"
            "# OPENAI_MODEL=gpt-4.1-mini\n"
        )
    content = _render_env_from_template(
        template=template,
        api_key=api_key,
        base_url=base_url,
        model=model,
    )
    env_file.write_text(content, encoding="utf-8")


def _run_init_wizard(
    *,
    workspace_root: Path | None,
    yes: bool,
    force: bool,
    api_key: str | None,
    base_url: str | None,
    model: str | None,
) -> Path:
    settings = Settings.load(workspace_root=workspace_root)
    env_file = _global_env_file()

    if env_file.exists() and not force:
        if yes:
            typer.echo(f"配置已存在，跳过写入: {env_file}")
            return env_file
        overwrite = typer.confirm(f"发现现有配置文件 {env_file}，是否覆盖？", default=False)
        if not overwrite:
            typer.echo("已取消覆盖，保持原配置不变。")
            return env_file

    resolved_api_key = (api_key if api_key is not None else settings.openai_api_key) or ""
    resolved_base_url = base_url or settings.openai_base_url
    resolved_model = model or settings.openai_model

    if not yes:
        typer.echo(f"工作区: {settings.workspace_root}")
        typer.echo(f"配置文件将写入: {env_file}")
        resolved_api_key = typer.prompt(
            "OPENAI_API_KEY（可留空，后续再填）",
            default=resolved_api_key,
            hide_input=True,
            show_default=False,
        )
        resolved_base_url = typer.prompt("OPENAI_BASE_URL", default=resolved_base_url)
        resolved_model = typer.prompt("OPENAI_MODEL", default=resolved_model)

    _write_global_env_file(
        env_file=env_file,
        api_key=resolved_api_key.strip() or None,
        base_url=resolved_base_url.strip(),
        model=resolved_model.strip(),
    )
    typer.echo(f"初始化完成: {env_file}")
    if not resolved_api_key.strip():
        typer.echo("提示: 当前未填写 OPENAI_API_KEY，后续运行前请补充。")
    return env_file


def _maybe_run_init_guide(*, workspace_root: Path | None, command_name: str) -> None:
    if command_name not in {"chat", "repl", "tui", "api"}:
        return
    settings = Settings.load(workspace_root=workspace_root)
    if settings.openai_api_key:
        return

    env_file = _global_env_file()
    env_vars_set = "OPENAI_API_KEY" in os.environ
    if env_vars_set:
        return

    typer.echo(f"未检测到 OPENAI_API_KEY（workspace={settings.workspace_root}）。")
    typer.echo(f"建议先初始化配置文件: {env_file}")

    if not sys.stdin.isatty():
        typer.echo("当前非交互终端，已跳过引导。可手动运行: ggbot init")
        return

    if typer.confirm("是否现在运行初始化向导？", default=True):
        _run_init_wizard(
            workspace_root=workspace_root,
            yes=False,
            force=False,
            api_key=None,
            base_url=None,
            model=None,
        )


def _most_recent_session_id(transcript_dir: Path) -> str | None:
    candidates = list(transcript_dir.glob("*.jsonl"))
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0].stem


def _format_ts(ts_ms: int | None) -> str:
    if ts_ms is None:
        return "--:--:--"
    try:
        return datetime.fromtimestamp(ts_ms / 1000).strftime("%H:%M:%S")
    except Exception:
        return "--:--:--"


def _parse_ts_ms(raw: object) -> int | None:
    if isinstance(raw, (int, float)):
        return int(raw)
    if isinstance(raw, str) and raw.isdigit():
        return int(raw)
    return None


def _render_event_line(
    ev: dict,
    *,
    include_system: bool,
    include_events: bool,
) -> str | None:
    event_type = str(ev.get("type") or "")
    ts_ms = _parse_ts_ms(ev.get("ts_ms"))

    if event_type == "model_message":
        data = ev.get("data") or {}
        try:
            msg = ChatMessage.model_validate(data)
        except Exception:
            return None

        if not include_system and msg.role == "system":
            return None
        return _render_log_message(msg, ts_ms=ts_ms)

    if not include_events:
        return None

    data = ev.get("data") or {}
    ts_prefix = f"{COLOR_DIM}[{_format_ts(ts_ms)}]{COLOR_RESET} "

    if event_type == "tool_call":
        name = str(data.get("name") or "<unknown>")
        if data.get("arguments") is not None:
            args_text = json.dumps(data.get("arguments"), ensure_ascii=False)
        else:
            args_text = str(data.get("raw_arguments") or "{}")
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_BLUE}tool_call{COLOR_RESET} name={COLOR_CYAN}{name}{COLOR_RESET} args={args_text}"

    if event_type == "tool_result":
        name = str(data.get("name") or "<unknown>")
        status = "error" if bool(data.get("error")) else "ok"
        status_color = COLOR_RED if status == "error" else COLOR_GREEN
        auto_healed = " auto_healed=true" if bool(data.get("auto_healed")) else ""
        content_len = int(data.get("content_len") or 0)
        return (
            f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_BLUE}tool_result{COLOR_RESET} "
            f"name={COLOR_CYAN}{name}{COLOR_RESET} status={status_color}{status}{COLOR_RESET} "
            f"content_len={COLOR_MAGENTA}{content_len}{COLOR_RESET}{auto_healed}"
        )

    if event_type == "provider_error":
        err = str(data.get("error") or "unknown")
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_RED}provider_error{COLOR_RESET} {err}"

    if event_type == "plan_update":
        plan = data.get("plan") or []
        lines = []
        for i, item in enumerate(plan, 1):
            status = "x" if item.get("completed") else " "
            tool = f" ({item['tool']})" if item.get("tool") else ""
            lines.append(f"  {i}. [{status}] {item.get('text')}{tool}")
        plan_text = "\n".join(lines)
        return f"{ts_prefix}{COLOR_YELLOW}[PLAN]{COLOR_RESET}\n{plan_text}"

    if event_type == "status":
        msg = str(data.get("message") or "")
        stage = data.get("stage")
        percent = data.get("percent")

        extras: list[str] = []
        if stage is not None:
            extras.append(f"stage={stage}")
        if percent is not None:
            extras.append(f"percent={percent}")

        extra_text = (" " + " ".join(extras)) if extras else ""
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_MAGENTA}status{COLOR_RESET}{extra_text} {msg}"

    if event_type == "tool_stream":
        name = str(data.get("name") or "<unknown>")
        chunk = str(data.get("chunk") or "")
        chunk = chunk.replace("\r", "")
        if len(chunk) > 200:
            chunk = chunk[:200] + "…"
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_BLUE}tool_stream{COLOR_RESET} name={COLOR_CYAN}{name}{COLOR_RESET} chunk={COLOR_DIM}{chunk!r}{COLOR_RESET}"

    if event_type == "turn_info":
        max_turns = int(data.get("max_turns") or 0)
        start_turn = int(data.get("start_turn") or 0)
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_GREEN}turn_info{COLOR_RESET} max_turns={COLOR_CYAN}{max_turns}{COLOR_RESET} start_turn={COLOR_CYAN}{start_turn}{COLOR_RESET}"

    if event_type == "turn_update":
        current_turn = int(data.get("current_turn") or 0)
        max_turns = int(data.get("max_turns") or 0)
        progress = f"{current_turn}/{max_turns}"
        progress_color = COLOR_GREEN if current_turn < max_turns else COLOR_YELLOW
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_GREEN}turn_update{COLOR_RESET} turn={progress_color}{progress}{COLOR_RESET}"

    if event_type == "turn_complete":
        turns_used = int(data.get("turns_used") or 0)
        max_turns = int(data.get("max_turns") or 0)
        completed = bool(data.get("completed"))
        status = "completed" if completed else "max_turns_reached"
        status_color = COLOR_GREEN if completed else COLOR_YELLOW
        return f"{ts_prefix}{COLOR_YELLOW}[EVENT]{COLOR_RESET} {COLOR_GREEN}turn_complete{COLOR_RESET} turns_used={COLOR_CYAN}{turns_used}{COLOR_RESET}/{COLOR_CYAN}{max_turns}{COLOR_RESET} status={status_color}{status}{COLOR_RESET}"

    return None


def _iter_rendered_log_lines(
    path: Path,
    *,
    include_system: bool,
    include_events: bool,
) -> list[str]:
    out: list[str] = []
    if not path.exists():
        return out

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
            except Exception:
                continue

            rendered = _render_event_line(
                ev,
                include_system=include_system,
                include_events=include_events,
            )
            if rendered is not None:
                out.append(rendered)

    return out


def _parse_rendered_event_line(
    line: str,
    *,
    include_system: bool,
    include_events: bool,
) -> str | None:
    try:
        ev = json.loads(line)
    except Exception:
        return None
    return _render_event_line(
        ev,
        include_system=include_system,
        include_events=include_events,
    )


def _render_log_message(msg: ChatMessage, *, ts_ms: int | None = None) -> str:
    ts_prefix = f"{COLOR_DIM}[{_format_ts(ts_ms)}]{COLOR_RESET} "

    # Determine role color
    if msg.role == "user":
        role_color = COLOR_GREEN
    elif msg.role == "assistant":
        if msg.tool_calls:
            role_color = COLOR_YELLOW
        else:
            role_color = COLOR_CYAN
    elif msg.role == "system":
        role_color = COLOR_MAGENTA
    elif msg.role == "tool":
        role_color = COLOR_BLUE
    elif msg.role == "thinking":
        role_color = COLOR_YELLOW + COLOR_DIM  # Dim yellow for thinking
    else:
        role_color = COLOR_WHITE

    # Format role label
    if msg.role == "tool":
        role_label = f"TOOL:{msg.name or 'tool'}"
    elif msg.role == "assistant" and msg.tool_calls:
        role_label = "ASSISTANT:tool_calls"
    else:
        role_label = msg.role.upper()

    colored_role = f"{role_color}[{role_label}]{COLOR_RESET}"

    content = (msg.content or "").strip()
    if not content and msg.tool_calls:
        calls = ", ".join(tc.function.name for tc in msg.tool_calls)
        content = f"(tool calls: {calls})"
    if not content:
        content = "(empty)"

    # 清理内容中的换行符，确保单行显示
    content = content.replace('\n', ' ').replace('\r', '')

    lines = content.splitlines()
    if len(lines) == 1:
        return f"{ts_prefix}{colored_role} {lines[0]}"

    first = f"{ts_prefix}{colored_role} {lines[0]}"
    rest = "\n".join(f"  {line}" for line in lines[1:])
    return f"{first}\n{rest}"




def _ensure_message_bootstrap(
    messages: list[ChatMessage],
    transcript: Transcript,
    *,
    system_message: ChatMessage | None = None,
) -> None:
    if messages and messages[0].role == "system":
        return
    msg = system_message or _default_system_message()
    messages.insert(0, msg)
    transcript.append("model_message", msg.model_dump(exclude_none=True))


def _handle_slash(line: str, *, registry: ToolRegistry, transcript: Transcript, messages: list[ChatMessage]) -> bool:
    # Returns True if handled.
    if not line.startswith("/"):
        return False

    parts = line.strip().split(" ", 2)
    cmd = parts[0].lower()

    if cmd in {"/exit", "/quit"}:
        raise typer.Exit(0)

    if cmd == "/read" and len(parts) >= 2:
        try:
            out = registry.call("file_read", {"path": parts[1]})
        except Exception as e:
            out = f"Tool error: {type(e).__name__}: {e}"
        print(out)
        sys_msg = ChatMessage(role="system", content=f"/read {parts[1]}\n\n{out}")
        messages.append(sys_msg)
        transcript.append("model_message", sys_msg.model_dump(exclude_none=True))
        return True

    if cmd == "/write" and len(parts) == 3:
        path = parts[1]
        content = parts[2]
        try:
            out = registry.call("file_write", {"path": path, "content": content})
        except Exception as e:
            out = f"Tool error: {type(e).__name__}: {e}"
        print(out)
        sys_msg = ChatMessage(role="system", content=f"/write {path}\n\n{out}")
        messages.append(sys_msg)
        transcript.append("model_message", sys_msg.model_dump(exclude_none=True))
        return True

    if cmd == "/workspace" and len(parts) >= 2:
        path = parts[1]
        try:
            out = registry.call("create_workspace", {"path": path})
        except Exception as e:
            out = f"Tool error: {type(e).__name__}: {e}"
        print(out)
        sys_msg = ChatMessage(role="system", content=f"/workspace {path}\n\n{out}")
        messages.append(sys_msg)
        transcript.append("model_message", sys_msg.model_dump(exclude_none=True))
        return True

    if cmd in {"/workspace_ls", "/ws"}:
        path = parts[1] if len(parts) >= 2 else "."
        try:
            out = registry.call("workspace_list", {"path": path})
        except Exception as e:
            out = f"Tool error: {type(e).__name__}: {e}"
        print(out)
        sys_msg = ChatMessage(role="system", content=f"/workspace_ls {path}\n\n{out}")
        messages.append(sys_msg)
        transcript.append("model_message", sys_msg.model_dump(exclude_none=True))
        return True

    if cmd == "/shell" and len(parts) >= 2:
        cmdline = line.strip()[len("/shell") :].strip()
        try:
            out = registry.call("shell_run", {"command": cmdline})
        except Exception as e:
            out = f"Tool error: {type(e).__name__}: {e}"
        print(out)
        sys_msg = ChatMessage(role="system", content=f"/shell {cmdline}\n\n{out}")
        messages.append(sys_msg)
        transcript.append("model_message", sys_msg.model_dump(exclude_none=True))
        return True

    if cmd == "/help":
        print(
            "Slash commands: /read <path>, /write <path> <content>, /workspace <path>, "
            "/workspace_ls [path], /shell <cmd>, /exit"
        )
        return True

    print("Unknown command. Use /help")
    return True


@app.command()
def chat(
    prompt: str = typer.Argument(..., help="User prompt"),
    resume: str | None = typer.Option(None, "--resume", help="Resume from an existing session id"),
    workspace_root: Path | None = typer.Option(None, help="Workspace root (sandbox)"),
    show_tools: bool = typer.Option(
        False,
        "--show-tools/--no-show-tools",
        help="Print tool outputs (e.g., file_read contents) to the terminal.",
    ),
    thinking: bool = typer.Option(
        None,
        "--thinking/--no-thinking",
        help="Enable thinking/reasoning output. Overrides config setting.",
    ),
):
    _maybe_run_init_guide(workspace_root=workspace_root, command_name="chat")
    app_session = create_app_session(
        workspace_root=workspace_root,
        resume=resume,
        default_session_name="chat",
    )
    settings = app_session.settings
    session_id = app_session.session_id
    transcript = app_session.transcript

    # Determine thinking setting: command line overrides config
    thinking_enabled = settings.thinking_enabled
    if thinking is not None:
        thinking_enabled = thinking

    bootstrap = create_agent_bootstrap(
        settings=settings,
        session_id=session_id,
        transcript=transcript,
        mode="chat",
        thinking_enabled=thinking_enabled,
    )
    runtime = bootstrap.runtime

    try:
        tool_context = bootstrap.tool_manager.create_tool_context(
            session_id=session_id,
            transcript=transcript,
            workspace_root=settings.workspace_root,
        )
        result = run_query(
            client=runtime.client,
            registry=runtime.registry,
            transcript=runtime.transcript,
            messages=runtime.messages,
            user_text=prompt,
            max_turns=settings.max_turns,
            stream_printer=_print_delta,
            tool_printer=_print_tool_output if show_tools else None,
            tool_context=tool_context,
            tool_limits=ToolLimits(
                max_tool_calls=settings.max_tool_calls,
                max_tool_calls_per_tool=settings.max_tool_calls_per_tool,
                max_tool_calls_same_args=settings.max_tool_calls_same_args,
            ),
            thinking_enabled=thinking_enabled,
        )
        consume_runtime_events(
            result.events,
            on_provider_error=lambda data: print(f"provider_error: {data.get('error', 'unknown')}"),
        )
        print("")
        print(f"\n[session_id={session_id}] transcript={transcript.path}")
    finally:
        bootstrap.client.close()


@app.command()
def repl(
    resume: str | None = typer.Option(None, "--resume", help="Resume from an existing session id"),
    workspace_root: Path | None = typer.Option(None, help="Workspace root (sandbox)"),
    show_tools: bool = typer.Option(
        True,
        "--show-tools/--no-show-tools",
        help="Print tool outputs (e.g., file_read contents) to the terminal.",
    ),
    thinking: bool = typer.Option(
        None,
        "--thinking/--no-thinking",
        help="Enable thinking/reasoning output. Overrides config setting.",
    ),
):
    _maybe_run_init_guide(workspace_root=workspace_root, command_name="repl")
    app_session = create_app_session(
        workspace_root=workspace_root,
        resume=resume,
        default_session_name="repl",
    )
    settings = app_session.settings
    session_id = app_session.session_id
    transcript = app_session.transcript

    # Determine thinking setting: command line overrides config
    thinking_enabled = settings.thinking_enabled
    if thinking is not None:
        thinking_enabled = thinking

    bootstrap = create_agent_bootstrap(
        settings=settings,
        session_id=session_id,
        transcript=transcript,
        mode="repl",
        thinking_enabled=thinking_enabled,
    )
    runtime = bootstrap.runtime

    print(f"GGbot REPL  session_id={session_id}")
    print("Type /help for commands. Ctrl+C to exit.")

    try:
        tool_context = bootstrap.tool_manager.create_tool_context(
            session_id=session_id,
            transcript=transcript,
            workspace_root=settings.workspace_root,
        )
        while True:
            try:
                line = input("> ")
            except (EOFError, KeyboardInterrupt):
                print("")
                break

            line = line.rstrip("\n")
            if not line.strip():
                continue

            if line.startswith("/"):
                _handle_slash(line, registry=runtime.registry, transcript=runtime.transcript, messages=runtime.messages)
                continue

            result = run_query(
                client=runtime.client,
                registry=runtime.registry,
                transcript=runtime.transcript,
                messages=runtime.messages,
                user_text=line,
                max_turns=settings.max_turns,
                stream_printer=_print_delta,
                tool_printer=_print_tool_output if show_tools else None,
                tool_context=tool_context,
                tool_limits=ToolLimits(
                    max_tool_calls=settings.max_tool_calls,
                    max_tool_calls_per_tool=settings.max_tool_calls_per_tool,
                    max_tool_calls_same_args=settings.max_tool_calls_same_args,
                ),
                thinking_enabled=thinking_enabled,
            )
            consume_runtime_events(
                result.events,
                on_provider_error=lambda data: print(f"provider_error: {data.get('error', 'unknown')}"),
            )
            print("")

    finally:
        bootstrap.client.close()
        print(f"[session_id={session_id}] transcript={transcript.path}")


@app.command()
def init(
    workspace_root: Path | None = typer.Option(None, "--workspace-root", help="Workspace root (sandbox)"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Use defaults and do not prompt."),
    force: bool = typer.Option(False, "--force", help="Overwrite existing .env file."),
    api_key: str | None = typer.Option(None, "--api-key", help="OPENAI_API_KEY value."),
    base_url: str | None = typer.Option(None, "--base-url", help="OPENAI_BASE_URL value."),
    model: str | None = typer.Option(None, "--model", help="OPENAI_MODEL value."),
) -> None:
    """Initialize workspace configuration with a guided wizard."""
    _run_init_wizard(
        workspace_root=workspace_root,
        yes=yes,
        force=force,
        api_key=api_key,
        base_url=base_url,
        model=model,
    )


@app.command()
def tui(
    resume: str | None = typer.Option(None, "--resume", help="Resume from an existing session id"),
    workspace_root: Path | None = typer.Option(None, help="Workspace root (sandbox)"),
):
    """Full-screen terminal UI (Textual)."""
    _maybe_run_init_guide(workspace_root=workspace_root, command_name="tui")
    from example.tui_frontend.tui import run_tui

    run_tui(
        resume=resume,
        workspace_root=workspace_root,
    )


@app.command("log")
def log_view(
    session: str | None = typer.Option(None, "--session", help="Session id to inspect."),
    workspace_root: Path | None = typer.Option(None, help="Workspace root (sandbox)."),
    tail: int = typer.Option(200, "--tail", min=1, max=5000, help="Show only the last N messages."),
    follow: bool = typer.Option(False, "--follow", "-f", help="Follow transcript in real time."),
    poll_ms: int = typer.Option(400, "--poll-ms", min=100, max=5000, help="Polling interval in follow mode."),
    include_events: bool = typer.Option(
        True,
        "--events/--no-events",
        help="Include runtime events such as tool_call/tool_result.",
    ),
    include_system: bool = typer.Option(
        False,
        "--include-system/--no-include-system",
        help="Include system messages in log output.",
    ),
) -> None:
    """Show transcript log in a dedicated terminal view."""

    app_session = create_app_session(
        workspace_root=workspace_root,
        resume=session,
        default_session_name="repl",
        prefer_recent=True,
    )
    settings = app_session.settings
    session_id = app_session.session_id
    transcript_dir = settings.resolved_transcript_dir()
    path = app_session.transcript.path

    if not path.exists():
        print(f"No transcript found for session_id={session_id}")
        print(f"transcript_dir={transcript_dir}")
        return

    lines = _iter_rendered_log_lines(
        path,
        include_system=include_system,
        include_events=include_events,
    )

    if not lines:
        print(f"Transcript is empty for session_id={session_id}")
        print(f"transcript={path}")
        if not follow:
            return

    shown = lines[-tail:]
    print(
        f"GGbot log  session_id={session_id}  total={len(lines)}  showing={len(shown)}"
    )
    print(f"transcript={path}")
    print("-" * 72)
    for item in shown:
        print(item)

    if not follow:
        return

    print("-" * 72)
    print("Following... Press Ctrl+C to stop.")
    sleep_s = poll_ms / 1000.0

    with path.open("r", encoding="utf-8") as f:
        f.seek(0, 2)
        try:
            while True:
                line = f.readline()
                if not line:
                    time.sleep(sleep_s)
                    continue

                rendered = _parse_rendered_event_line(
                    line,
                    include_system=include_system,
                    include_events=include_events,
                )
                if rendered is None:
                    continue
                print(rendered)
        except KeyboardInterrupt:
            print("\nStopped following.")

@app.command()
def api(
    host: str = typer.Option("127.0.0.1", "--host", "-h", help="服务器主机地址"),
    port: int = typer.Option(8000, "--port", "-p", help="服务器端口"),
    workspace_root: Optional[Path] = typer.Option(None, "--workspace-root", help="工作空间根目录"),
    resume: Optional[str] = typer.Option(None, "--resume", help="恢复指定会话"),
    log_level: str = typer.Option("info", "--log-level", "-l", help="日志级别 (debug/info/warning/error)"),
):
    """启动GGbot API服务器"""
    _maybe_run_init_guide(workspace_root=workspace_root, command_name="api")
    import logging
    
    try:
        from .api.server import run_api_server
    except ImportError:
        print("错误：API服务器模块不可用")
        print("请确保已安装FastAPI和uvicorn：pip install fastapi uvicorn")
        return

    from .app.app_bootstrap import create_agent_bootstrap, create_app_session

    # ========== 1. 配置日志（应用入口职责）==========
    level_map = {
        "debug": logging.DEBUG,
        "info": logging.INFO,
        "warning": logging.WARNING,
        "error": logging.ERROR,
    }
    log_level_value = level_map.get(log_level.lower(), logging.INFO)
    
    # 配置根日志器 - 只在入口配置一次
    logging.basicConfig(
        level=log_level_value,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    
    # 设置第三方库的日志级别（避免噪音）
    logging.getLogger("uvicorn.access").setLevel(logging.WARNING)
    logging.getLogger("httpx").setLevel(logging.WARNING)
    
    logger = logging.getLogger("ggbot.cli")
    
    # ========== 2. 显示启动信息 ==========
    print(f"\n{'='*60}")
    print(f"启动 GGbot API 服务器")
    print(f"{'='*60}")
    print(f"地址: http://{host}:{port}")
    print(f"WebSocket: ws://{host}:{port}/ws")
    print(f"日志级别: {log_level.upper()}")
    print(f"工作目录: {workspace_root or '默认'}")
    if resume:
        print(f"恢复会话: {resume}")
    print(f"{'='*60}\n")
    
    # ========== 3. 创建资源 ==========
    app_session = None
    bootstrap = None
    
    try:
        # 创建应用会话
        logger.info(f"创建应用会话: workspace={workspace_root}, resume={resume}")
        app_session = create_app_session(
            workspace_root=workspace_root,
            resume=resume,
            default_session_name="chat",
            prefer_recent=True,
        )
        logger.info(f"会话已创建: session_id={app_session.session_id}")
        
        # 创建 agent bootstrap
        logger.info("初始化 Agent 运行时...")
        bootstrap = create_agent_bootstrap(
            settings=app_session.settings,
            session_id=app_session.session_id,
            transcript=app_session.transcript,
            mode="chat",
            thinking_enabled=app_session.settings.thinking_enabled,
            shell_confirm_callback=_make_api_shell_confirm_callback(logger),
        )
        logger.info(f"Agent 运行时已初始化")
        
        # ========== 4. 运行API服务器（阻塞）==========
        logger.info(f"启动 API 服务器: {host}:{port}")
        run_api_server(
            runtime=bootstrap.runtime,
            host=host,
            port=port,
        )
        
    except KeyboardInterrupt:
        print("\n\n收到中断信号，正在关闭服务器...")
        logger.info("收到 KeyboardInterrupt，服务器正在关闭")
        
    except Exception as e:
        logger.error(f"启动API服务器失败: {e}", exc_info=True)
        print(f"\n错误: 启动API服务器失败")
        print(f"详情: {e}\n")
        raise typer.Exit(code=1)
        
    finally:
        # ========== 5. 清理资源 ==========
        print("\n正在清理资源...")
        
        if bootstrap:
            logger.info("关闭 Agent 客户端连接...")
            try:
                bootstrap.client.close()
                logger.debug("Agent 客户端已关闭")
            except Exception as e:
                logger.error(f"关闭 Agent 客户端失败: {e}")
        
        # AppSession 通常不需要显式保存，transcript 会在运行时自动持久化
        if app_session:
            logger.debug("会话资源已释放")
        
        print("资源清理完成")
        print("服务器已停止\n")
        logger.info("API 服务器已完全关闭")
